### PR TITLE
Added PLAYER:LookAt

### PR DESCRIPTION
**Pull request by NanoAi**
Added `PLAYER:LookAt` also added a misc.lua for various short functions that don't really need their own file.

### CODE REVIEW

**Comment by Earu** [comment]
Not the right place, you should push that into inserts/preload
@LuaTenshi

**Comment by CapsAdmin** [comment]
Try not to add stuff to player metatable. I'm not saying don't at all but in the long run it's confusing for people who read the code.

You're only using this in one place, can it not just be a local function?

**Comment by NanoAi** [comment]
Actually it was already in the goto code you have, and was checked as a
player function. So I just added it to the meta for consistency.

**Comment by Earu** [comment]
Still its in the wrong place, at least do it in a preload folder

**Comment by NanoAi** [comment]
Then move it to the right place?

**Comment by NanoAi** [comment]
I can't move it currently as I'm not at home and have no idea how to do it
on mobile. You can try to move it now as when I made the pull I allowed
edits but if you don't want to or just can't be asked I'll move it into the
correct location when I get home.

**Comment by CapsAdmin** [comment]
It's  leftover code from metastruct. I think Python1320 wrote it. My point still stands though.

If you find silly things like this feel free to correct them. Of course consistency is nice but we or I can write bad code as well.

If you had direct commit access I probably wouldn't care (or I'd fix it in a refactor commit or something) but because of how pull requests work you tend to be more critical.

**Pull request merged**
